export const ActionTypes = {
    GET_MOVIES = "GET_MOVIES",
    GET_SINGLE_MOVIE: "GET_SINGLE_MOVIE",
    GET_MOVIE_GENRE: "GET_MOVIE_GENRE",
    GET_TVSHOWS: "GET_TVSHOWS",
    GET_SINGLE_TVSHOW: "GET_SINGLE_TVSHOW",
    GET_SINGLE_TVSHOW_SEASON: "GET_SINGLE_TVSHOW_SEASON"
};